MODULE ADDITIONAL_MOD
USE PARKIND1   ,ONLY: JPIM, JPRB, JPRM
IMPLICIT NONE
SAVE
INTEGER(KIND=JPIM)  ::  IFIRSTIN

CONTAINS
SUBROUTINE RESTART_INIT
  USE MOD_PROG   ,ONLY: D2RIVSTO_IN, D2FLDSTO_IN, D2RIVOUT_IN, D2FLDOUT_IN, D1PTHFLW_IN
  USE MOD_PROG   ,ONLY: D2RIVSTO_OUT,D2FLDSTO_OUT,D2RIVOUT_OUT,D2FLDOUT_OUT,D1PTHFLW_OUT, D2RUNOFF, &
       D2RIVOUT_PRE,D2FLDOUT_PRE,D1PTHFLW_PRE,D2RIVDPH_PRE,D2FLDSTO_PRE
  USE MOD_INPUT  ,ONLY: DT,DT_DEF
  DT=86400
  DT_DEF=DT
  !!D2RIVOUT_OUT=D2RIVOUT_PRE
  !!D2FLDOUT_OUT=D2FLDOUT_PRE
  !!D1PTHFLW_PRE(:,:) = 0._JPRB
  !!D1PTHFLW_OUT(:,:)=D1PTHFLW_PRE(:,:)
  !!D2RIVSTO_IN(:,:)=D2RIVSTO_OUT(:,:)
  !!D2FLDSTO_IN(:,:)=D2FLDSTO_OUT(:,:)
  !!D2RIVOUT_IN(:,:)=D2RIVOUT_OUT(:,:)
  !!D2FLDOUT_IN(:,:)=D2FLDOUT_OUT(:,:)
  !!D1PTHFLW_IN(:,:)=D1PTHFLW_OUT(:,:)
  !!D2RUNOFF(:,:)=0._JPRB
END SUBROUTINE RESTART_INIT

SUBROUTINE CLEANUP_TSTP

  USE MOD_DIAG   ,ONLY: D2RIVINF, D2RIVDPH, D2RIVVEL, D2FLDINF, D2FLDDPH, D2FLDFRC, D2FLDARE,&
       D2PTHOUT, D2PTHINF, D2SFCELV, D2OUTFLW, D2STORGE
  USE MOD_DIAG   ,ONLY: D2OUTFLW_AVG, D2RIVOUT_AVG, D2FLDOUT_AVG, D2RIVVEL_AVG, D2PTHOUT_AVG, D1PTHFLW_AVG, D2OUTINS, NADD

  USE MOD_PROG   ,ONLY: D2RIVSTO_IN, D2FLDSTO_IN, D2RIVOUT_IN, D2FLDOUT_IN, D1PTHFLW_IN
  USE MOD_PROG   ,ONLY: D2RIVSTO_OUT,D2FLDSTO_OUT,D2RIVOUT_OUT,D2FLDOUT_OUT,D1PTHFLW_OUT, D2RUNOFF, &
       D2RIVOUT_PRE,D2FLDOUT_PRE,D1PTHFLW_PRE,D2RIVDPH_PRE,D2FLDSTO_PRE

  DEALLOCATE(D2RIVINF)
  DEALLOCATE(D2RIVDPH)
  DEALLOCATE(D2RIVVEL)
  DEALLOCATE(D2FLDINF)
  DEALLOCATE(D2FLDDPH)
  DEALLOCATE(D2FLDFRC)
  DEALLOCATE(D2FLDARE)
  DEALLOCATE(D2PTHOUT)
  DEALLOCATE(D2PTHINF)
  DEALLOCATE(D2SFCELV)
  DEALLOCATE(D2OUTFLW)
  DEALLOCATE(D2STORGE)
  DEALLOCATE(D2RIVOUT_AVG)
  DEALLOCATE(D2FLDOUT_AVG)
  DEALLOCATE(D2RIVVEL_AVG)
  DEALLOCATE(D2PTHOUT_AVG)
  DEALLOCATE(D2OUTFLW_AVG)
  DEALLOCATE(D1PTHFLW_AVG)
  DEALLOCATE(D2OUTINS)

  DEALLOCATE(D2RUNOFF)
  DEALLOCATE(D2RIVSTO_IN)
  DEALLOCATE(D2FLDSTO_IN)
  DEALLOCATE(D2RIVOUT_IN)
  DEALLOCATE(D2FLDOUT_IN)
  DEALLOCATE(D2RIVSTO_OUT)
  DEALLOCATE(D2FLDSTO_OUT)
  DEALLOCATE(D2RIVOUT_OUT)
  DEALLOCATE(D2FLDOUT_OUT)
  DEALLOCATE(D2RIVOUT_PRE)
  DEALLOCATE(D2FLDOUT_PRE)
  DEALLOCATE(D2RIVDPH_PRE)
  DEALLOCATE(D2FLDSTO_PRE)
  DEALLOCATE(D1PTHFLW_IN)
  DEALLOCATE(D1PTHFLW_OUT)
  DEALLOCATE(D1PTHFLW_PRE)
END SUBROUTINE CLEANUP_TSTP

END MODULE ADDITIONAL_MOD
